#Site Setting
title: Modulab Data Lab Pages
logo: /assets/img/logo.jpeg
description: Here is Modulabs DataLAB warehouse.//여기는 데이터랩 깃페이지 입니다.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

#Build Setting

markdown : kramdown
permalink : pretty
paginate : 5
